require("config.lazy")
require("config.options") 
require("config.mapping")
require("config.color")

-- Plugins
require("plugins.mason")
require("plugins.treesitter")
require("plugins.neotree")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.conform")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.dap")
require("plugins.gitsigns")
require("plugins.flutter")
require("plugins.hex")
