return {
  "romus204/tree-sitter-manager.nvim",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "css",
      "csv",
      "cuda",
      "dart",
      "dockerfile",
      "doxygen",
      "ecma",
      "html",
      "html_tags",
      "javascript",
      "jsdoc",
      "json",
      "jsx",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "rust",
      "scss",
      "sql",
      "tsv",
      "tsx",
      "typescript",
      "typst",
      "yaml",
    },
  },
}
